// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW6ZWS7Mj295gM6D8XQFtr84g0T-DjehM',
    appId: '1:927971756351:web:eb6c3e1acdf757da962b8a',
    messagingSenderId: '927971756351',
    projectId: 'doctorate-9d101',
    authDomain: 'doctorate-9d101.firebaseapp.com',
    storageBucket: 'doctorate-9d101.firebasestorage.app',
    measurementId: 'G-QNTN0CKNX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuF8EemSlavdUweJEDC_Y_jUf5SB46fd8',
    appId: '1:927971756351:android:4c14f06c4a5f6a7a962b8a',
    messagingSenderId: '927971756351',
    projectId: 'doctorate-9d101',
    storageBucket: 'doctorate-9d101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu1j-jhTD-WZu_Rn_aRArgpXW6muLBrSs',
    appId: '1:927971756351:ios:17d82eebef30c6bb962b8a',
    messagingSenderId: '927971756351',
    projectId: 'doctorate-9d101',
    storageBucket: 'doctorate-9d101.firebasestorage.app',
    iosBundleId: 'com.example.docrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu1j-jhTD-WZu_Rn_aRArgpXW6muLBrSs',
    appId: '1:927971756351:ios:17d82eebef30c6bb962b8a',
    messagingSenderId: '927971756351',
    projectId: 'doctorate-9d101',
    storageBucket: 'doctorate-9d101.firebasestorage.app',
    iosBundleId: 'com.example.docrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW6ZWS7Mj295gM6D8XQFtr84g0T-DjehM',
    appId: '1:927971756351:web:62e1c3d9f3b62976962b8a',
    messagingSenderId: '927971756351',
    projectId: 'doctorate-9d101',
    authDomain: 'doctorate-9d101.firebaseapp.com',
    storageBucket: 'doctorate-9d101.firebasestorage.app',
    measurementId: 'G-6H7EWQFJ40',
  );

}